name: stat-rethink2-pymc-v6
channels:
  - conda-forge
dependencies:
  - python=3.12
  - arviz
  - asttokens
  - cached-property
  - cached_property
  - cachetools
  - cairo
  - certifi
  - cloudpickle
  - comm
  - cons
  - contourpy
  - cycler
  - debugpy
  - decorator
  - etuples
  - exceptiongroup
  - executing
  - expat
  - fastprogress
  - filelock
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - fribidi
  - gettext
  - graphite2
  - graphviz
  - gts
  - h5netcdf
  - h5py
  - harfbuzz
  - hdf5
  - icu
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - ipywidgets
  - jedi
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libcurl
  - libdeflate
  - libffi
  - libgd
  - libglib
  - libiconv
  - libjpeg-turbo
  - libpng
  - libsodium
  - libsqlite
  - libssh2
  - libtiff
  - libwebp
  - libwebp-base
  - libxml2
  - libzlib
  - logical-unification
  - matplotlib-base
  - matplotlib-inline
  - minikanren
  - mkl
  - mkl-service
  - multipledispatch
  - munkres
  - nest-asyncio
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pango
  - parso
  - patsy
  - pcre2
  - pickleshare
  - pillow
  - pip
  - pixman
  - platformdirs
  - psutil
  - pure_eval
  - pygments
  - pymc~=6.2
  - pymc-base
  - pyparsing
  - pytensor
  - pytensor-base
  - python-dateutil
  - python-graphviz
  - python-tzdata
  - pytz
  - pyzmq
  - scipy
  - seaborn
  - setuptools
  - six
  - stack_data
  - statsmodels
  - tbb
  - tk
  - toolz
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - wheel
  - xarray
  - xarray-einstats
  - xz
  - zeromq
  - zipp
  - zstd
  - pip:
    - "git+https://github.com/BirkhoffG/causalgraphicalmodels.git@master"
    - cfgv
    - daft
    - distlib
    - identify
    - networkx
    - nodeenv
    - pre-commit
    - prompt-toolkit
    - pyyaml
    - stack-data
    - virtualenv
    - watermark
    - wcwidth